-- FOR ROSEPINE
-- require("rose-pine").setup({
-- 	--- @usage "auto"|"main"|"moon"|"dawn"
-- 	variant = "moon",
-- 	bold_vert_split = true,
-- 	dim_nc_background = false,
-- 	disable_background = true,
-- 	disable_float_background = false,
-- 	disable_italics = true,
-- 
-- 	highlight_groups = {
-- 		ColorColumn = { bg = "surface" },
-- 
-- 		StatusLine = { fg = "love", bg = "love", blend = 10 },
-- 		StatusLineNC = { fg = "subtle", bg = "surface" },
-- 
-- 		IncSearch = { bg = "muted", fg = "base", inherit = false },
-- 	}
-- })

-- Set colorscheme after options
vim.cmd("colorscheme tokyonight")
